# Spins up all 3 components locally:
# - Edge device
# - Cloud server
# - Dashboard
# - Database

services:

  edge-client:
    image: edge-client
    build:
      context: ./edge-device
      dockerfile: Dockerfile.edge
    environment:
      - SERVER_ADDRESS=tcp://cloud-server:5555
      - CITY=Berlin
    networks:
      - my-shared-network
    
  edge-client-2:
    image: edge-client
    build:
      context: ./edge-device
      dockerfile: Dockerfile.edge
    environment:
      - SERVER_ADDRESS=tcp://cloud-server:5555
      - CITY=Hamburg
    networks:
      - my-shared-network

  edge-client-3:
    image: edge-client
    build:
      context: ./edge-device
      dockerfile: Dockerfile.edge
    environment:
      - SERVER_ADDRESS=tcp://cloud-server:5555
      - CITY=Munich
    networks:
      - my-shared-network

  cloud-server:
    image: cloud-server
    build:
      context: ./cloud-server
      dockerfile: Dockerfile.cloud
    environment:
      - SERVER_ENDPOINT=http://cloud-backend:5000
    networks:
      - my-shared-network
    ports:
      - "5555:5555"

  cloud-backend:
    image: cloud-backend
    build:
      context: ./cloud-backend
      dockerfile: Dockerfile.backend
    ports:
      - "5000:5000"
    networks:
      - my-shared-network

networks:
  my-shared-network: {}