FROM python:3.8-slim-buster

EXPOSE 5000
ENV FLASK_APP="main.py"

WORKDIR /python-docker

COPY requirements.txt requirements.txt
RUN pip3 install -r requirements.txt

COPY . .

CMD ["flask", "run", "--host=0.0.0.0"]