FROM python:3.10-slim-buster

ENV INTERNAL_MESSAGE_CACHE_MAX_QUEUE_LENGTH 0

WORKDIR /app

COPY requirements.txt requirements.txt
RUN pip3 install -r requirements.txt

COPY . .

EXPOSE 5555

CMD ["python3", "server.py"]